name: 'APIM Terraform CI'

on:
  pull_request:
    paths:
      - 'apim/**'
      - 'terraform.tfvars'
      - 'terraform.tfbackend'
      - '.github/workflows/apim-ci.yml'
    branches:
      - main

permissions:
  id-token: write      # Required for OIDC login in reusable workflow
  contents: read       # Required for checkout
  pull-requests: write # Required for PR commenting in reusable workflow

jobs:
  terraform_ci:
    name: 'Terraform CI (APIM - Dev Env)'
    uses: greg-court/cicd-templates/.github/workflows/terraform-ci.yaml@main
    with:
      working_directory: 'apim'
      tfvars_paths: '["../terraform.tfvars", "environments/dev.tfvars"]'
      tfbackend_path: '../terraform.tfbackend'
      backend_config_overrides: '{"key": "apim.tfstate", "container_name": "sub-dev-tfstate"}'
      environment_name: 'dev-plan'
    secrets: inherit