name: 'APIM Terraform CI'

on:
  pull_request:
    paths:
      - 'apim/**'
      - 'shared.tfvars'
      - '.github/workflows/apim-ci.yaml'
    branches:
      - main

permissions:
  id-token: write      # Required for OIDC login in reusable workflow
  contents: read       # Required for checkout
  pull-requests: write # Required for PR commenting in reusable workflow

jobs:
  terraform_ci:
    name: 'Terraform CI (APIM - Dev Env)'
    uses: greg-court/cicd-templates/.github/workflows/terraform-ci.yaml@main
    with:
      working_directory: 'apim'
      tfvars_paths: '["../shared.tfvars", "environments/dev.tfvars"]'
      terraform_backend_key: 'apim.tfstate'
      environment_name: 'dev-plan'
    secrets: inherit
