name: 'APIM Terraform CD'

on:
  push:
    branches:
      - main
    paths:
      - 'apim/**'
      - 'terraform.tfvars'
      - 'terraform.tfbackend'
      - '.github/workflows/apim-cd.yaml'
  workflow_dispatch:
    inputs:
      tf_action:
        description: "Terraform action ('apply' or 'destroy')"
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write # Required for OIDC login in reusable workflow
  contents: read  # Required for checkout

jobs:
  deploy_dev:
    name: 'Deploy APIM Dev'
    uses: greg-court/cicd-templates/.github/workflows/terraform-cd.yaml@main
    with:
      working_directory: 'apim'
      tfvars_paths: '["../terraform.tfvars", "environments/dev.tfvars"]'
      tfbackend_path: '../terraform.tfbackend'
      job_prefix: 'dev'
      plan_environment_name: 'dev-plan'
      apply_environment_name: 'dev-apply'
      backend_config_overrides: '{"key": "apim.tfstate", "container_name": "sub-dev-tfstate"}'
      tf_action: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tf_action || 'apply' }}
    secrets: inherit

  deploy_prod:
    name: 'Deploy APIM Prod'
    needs: deploy_dev
    if: needs.deploy_dev.result == 'success'
    uses: greg-court/cicd-templates/.github/workflows/terraform-cd.yaml@main
    with:
      working_directory: 'apim'
      tfvars_paths: '["../terraform.tfvars", "environments/prod.tfvars"]'
      tfbackend_path: '../terraform.tfbackend'
      job_prefix: 'prod'
      plan_environment_name: 'prod-plan'
      apply_environment_name: 'prod-apply'
      backend_config_overrides: '{"key": "apim.tfstate", "container_name": "sub-prod-tfstate"}'
      tf_action: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tf_action || 'apply' }}
    secrets: inherit