name: 'APIM Terraform CD'

on:
  push:
    branches:
      - main
    paths:
      - 'apim/**'
      - 'terraform.tfvars'
      - 'terraform.tfbackend'
      - '.github/workflows/apim-cd.yaml'
  workflow_dispatch:
    inputs:
      tf_action:
        description: "Terraform action ('apply' or 'destroy')"
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  deploy_dev:
    name: 'Deploy APIM Dev'
    uses: greg-court/cicd-templates/.github/workflows/terraform-cd.yaml@main
    with:
      working_directory: 'apim'
      tfvars_paths: '["../shared.tfvars", "environments/dev.tfvars"]'
      job_prefix: 'dev'
      plan_environment_name: 'dev-plan'
      apply_environment_name: 'dev-apply'
      terraform_backend_key: 'apim.tfstate'
      tf_action: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tf_action || 'apply' }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      BACKEND_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID_MANAGEMENT }}
      BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
      BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME}}
      BACKEND_STORAGE_CONTAINER_NAME: ${{ secrets.BACKEND_STORAGE_CONTAINER_NAME }}

  deploy_prod:
    name: 'Deploy APIM Prod'
    needs: deploy_dev
    if: needs.deploy_dev.result == 'success'
    uses: greg-court/cicd-templates/.github/workflows/terraform-cd.yaml@main
    with:
      working_directory: 'apim'
      tfvars_paths: '["../shared.tfvars", "environments/prod.tfvars"]'
      job_prefix: 'prod'
      plan_environment_name: 'prod-plan'
      apply_environment_name: 'prod-apply'
      terraform_backend_key: 'apim.tfstate'
      tf_action: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tf_action || 'apply' }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      BACKEND_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID_MANAGEMENT }}
      BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
      BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME}}
      BACKEND_STORAGE_CONTAINER_NAME: ${{ secrets.BACKEND_STORAGE_CONTAINER_NAME }}